# Add custom env variables to kyselyynohjaus.env file in this folder. Format: DB__MIGRATION_USER=username = {:db {:migration-user username}}

version: "3.9"
services:
  kyselyynohjaus:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - kyselyynohjaus.env
    volumes:
      - type: bind
        target: /kyselyynohjaus/logs
        source: logs
